spring.application.name=webapi
spring.datasource.url=jdbc:postgresql://localhost:5433/online_store_shop
spring.datasource.username=admin
spring.datasource.password=12345
server.port=8081
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect